
export const ADD_MODULE_INGREDIENT: 'ADD_MODULE_INGREDIENT' = 'ADD_MODULE_INGREDIENT';
export const DELETE_MODULE_INGREDIENT: 'DELETE_MODULE_INGREDIENT' = 'DELETE_MODULE_INGREDIENT';
export const MOVE_MODULE_INGREDIENT: 'MOVE_MODULE_INGREDIENT' = 'MOVE_MODULE_INGREDIENT';
export const RESET_MODULE_INGREDIENTS: 'RESET_MODULE_INGREDIENTS' = 'RESET_MODULE_INGREDIENTS';
