export const GET_MENU_INGREDIENTS_REQUEST: 'GET_MENU_INGREDIENTS_REQUEST' = 'GET_MENU_INGREDIENTS_REQUEST';
export const GET_MENU_INGREDIENTS_SUCCESS: 'GET_MENU_INGREDIENTS_SUCCESS' = 'GET_MENU_INGREDIENTS_SUCCESS';
export const GET_MENU_INGREDIENTS_FAILED: 'GET_MENU_INGREDIENTS_FAILED' = 'GET_MENU_INGREDIENTS_FAILED';
