export const SHOW_MENU_INGREDIENT_REQUEST: 'SHOW_MENU_INGREDIENT_REQUEST' = 'SHOW_MENU_INGREDIENT_REQUEST';
export const HIDE_MENU_INGREDIENT_REQUEST: 'HIDE_MENU_INGREDIENT_REQUEST' = 'HIDE_MENU_INGREDIENT_REQUEST';
